### ISSUE TITLE
Setup basic server infrastructure

### ISSUE THREAD

**Issue by swzr** [mif-sge/verkehr#10]
Setup a basic server infrastructure using [Node.js](https://github.com/nodejs/node) and [hapi.js](https://github.com/hapijs/hapi).
The goal is to have a basic setup which can be easily extended to serve internal and external apis.

**Comment by swzr** [comment]
Added some explanations on how to start the server application: 019d6855c647e07bd3ae94e150d8998f4a554611.
Would be great if someone could verify it's successfully running on different systems.
@oxanaZh @xTeufelx @AlexJ2017

**Comment by xTeufelx** [comment]
It runs sucessfully on my system (Currently displaying "Hello World")
