### ISSUE TITLE
Define and document used programming languages, tools and their respective versions

### ISSUE THREAD

**Issue by swzr** [mif-sge/verkehr#15]
We need to define and document all programming languages, tools, frameworks and of course their respective versions.

The backend server currently uses the following runtime and packages:
- Node.js >= 10.15.3
- @hapi/hapi = 18.x.x
- @hapi/glue = 6.x.x
- @hapi/boom = 7.x.x
- winston = ^3.2.1
- confidence = 4.x.x
- dotenv = 8.x.x 

If needed, the packages could be pinned to specific versions, but the total number of used packages is still subject to change.

My suggestions for the other languages, tools, etc. would be the following ones:
- Neo4j = 3.5.3
- Python = 3.7

@AlexJ2017 @xTeufelx 
Which packages/tools are used to develop the frontend?

@Zakor11 
How specific should the list be? Would this be enough?

**Comment by Zakor11** [comment]
This would be fine and, as long as higher versions are compatible, pinning won't be necessary. New Versions should be updated in the specs document of course.

**Comment by Zakor11** [comment]
thanks for the list, it was added to the document
