### ISSUE TITLE
Setup local docker network

### ISSUE THREAD

**Issue by xTeufelx** [mif-sge/verkehr#20]
- [x] frontend runs in docker container
- [x] server runs in docker container
- [x] database runs in docker container
- [x] frontend communicates with server
- [x] server communicates with database

**Comment by swzr** [comment]
@LSteinkamp 
Could you please setup a docker-compose.yml for the entire project?

**Comment by LSteinkamp** [comment]
Is in Branch feature/basic_client_server_communication
