### ISSUE TITLE
Setup reverse proxy

### ISSUE THREAD

**Issue by swzr** [mif-sge/verkehr#25]
In order to publicly serve our frontend and our APIs, a reverse proxy will be needed.
It will function as a communication interface between our internal applications and the outside world.
Additionally, it will provide secure connections via TLS/SSL and load balancing or caching if necessary.

My suggestion would be [nginx](https://www.nginx.com/).
It provides all necessary features, is highly optimized, easily configurable and has a small footprint.
Another option would be [Apache httpd](https://httpd.apache.org/).

**Comment by swzr** [comment]
@LSteinkamp 
The proxy will eventually need its own docker container. 
We'll update you on needed configurations as soon as possible.

**Comment by LSteinkamp** [comment]
Is there any update regarding the Proxy?

**Comment by swzr** [comment]
> Is there any update regarding the Proxy?

Still WIP. I'll provide a nginx.conf as soon as possible.
