### ISSUE TITLE
Fix server application failing in docker container

### ISSUE THREAD

**Issue by swzr** [mif-sge/verkehr#27]
As of now the backend server application is not able to run in a docker container running linux.

After thoroughly researching the reasons why, the following causes were found:
- difference between how Windows and linux distributions handle file paths
- difference between how Windows and linux distributions handle upper and lower casing

**Comment by Zakor11** [comment]
Is this fixable on your side? Or do you need different docker settings?

**Comment by swzr** [comment]
> Is this fixable on your side? Or do you need different docker settings?

Up until now no additional docker settings are required. 
Will keep you updated, but I think it's manageable at the application layer.
