### ISSUE TITLE
Implement route planning

### ISSUE THREAD

**Issue by swzr** [mif-sge/verkehr#50]
In order to create bus schedules, we need to implement an algorithm for route planning and optimizations.

Current considerations include:
- [Python](https://www.python.org/) as implementation language
- [Google OR-Tools](https://github.com/google/or-tools) as optimization tools
- [AWS Lambda](https://aws.amazon.com/lambda/features/) as runtime

**Comment by swzr** [comment]
There seem to be some issues regarding AWS Lambda and OR-Tools.

To circumvent this, we will setup a dedicated computing node.
I've already spoken to @LSteinkamp about docker and kubernetes integration.

First results will be available towards evening.

**Comment by Zakor11** [comment]
Any updates on this one within the last week? Is it done?

**Comment by swzr** [comment]
> Any updates on this one within the last week? Is it done?

Still working on it. Had to wait until real data was available. Now I'm adjusting the queries and routines to fit our specifications.
